// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, formDataBodySerializer, type Options as Options2, type RequestResult, type TDataShape } from './client';
import { client } from './client.gen';
import type { GetHealthData, GetHealthResponses, PostApiPdfFromHtmlBundleRenderData, PostApiPdfFromHtmlBundleRenderResponses, PostApiPdfFromHtmlRenderData, PostApiPdfFromHtmlRenderResponses, PostApiPdfFromHtmlTemplateRenderData, PostApiPdfFromHtmlTemplateRenderResponses, PostApiPdfFromHtmlTemplateTestData, PostApiPdfFromHtmlTemplateTestResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Render PDF from bundle including HTML(-Template) with model and assets provided in form-data (keys: bundle, model)
 *
 * Returns PDF file generated from bundle (Zip-File) of HTML or HTML template of body, header, footer and assets. The index.html file in the Zip-Bundle is required
 */
export const postApiPdfFromHtmlBundleRender = <ThrowOnError extends boolean = false>(options: Options<PostApiPdfFromHtmlBundleRenderData, ThrowOnError>): RequestResult<PostApiPdfFromHtmlBundleRenderResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostApiPdfFromHtmlBundleRenderResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    responseType: 'blob',
    url: '/api/pdf/from/html-bundle/render',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Render PDF from HTML template
 *
 * Returns PDF file generated from HTML template plus model of body, header and footer
 */
export const postApiPdfFromHtmlTemplateRender = <ThrowOnError extends boolean = false>(options: Options<PostApiPdfFromHtmlTemplateRenderData, ThrowOnError>): RequestResult<PostApiPdfFromHtmlTemplateRenderResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostApiPdfFromHtmlTemplateRenderResponses, unknown, ThrowOnError>({
    responseType: 'blob',
    url: '/api/pdf/from/html-template/render',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Test HTML template matching model
 *
 * Returns information about matching model data to template
 */
export const postApiPdfFromHtmlTemplateTest = <ThrowOnError extends boolean = false>(options: Options<PostApiPdfFromHtmlTemplateTestData, ThrowOnError>): RequestResult<PostApiPdfFromHtmlTemplateTestResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostApiPdfFromHtmlTemplateTestResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/pdf/from/html-template/test',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Render PDF from HTML
 *
 * Returns PDF file generated from HTML of body, header and footer
 */
export const postApiPdfFromHtmlRender = <ThrowOnError extends boolean = false>(options: Options<PostApiPdfFromHtmlRenderData, ThrowOnError>): RequestResult<PostApiPdfFromHtmlRenderResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostApiPdfFromHtmlRenderResponses, unknown, ThrowOnError>({
    responseType: 'blob',
    url: '/api/pdf/from/html/render',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Liveness probe for this service
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>): RequestResult<GetHealthResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({
    responseType: 'text',
    url: '/health',
    ...options
});
