// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:8000' | (string & {});
};

export type PageSize = {
    /**
     * in mm
     */
    height?: number;
    /**
     * in mm
     */
    width?: number;
};

export type RenderData = {
    /**
     * Optional html for footer. If empty, the footer html will be parsed from main html (<PdfFooter></PdfFooter>).
     */
    footerHtml?: string;
    /**
     * Optional html for header. If empty, the header html will be parsed from main html (<PdfHeader></PdfHeader>).
     */
    headerHtml?: string;
    html?: string;
    options?: RenderOptions;
};

export type RenderOptions = {
    excludeBuiltinStyles?: boolean;
    includeRenderLog?: boolean;
    landscape?: boolean;
    /**
     * margins in mm; fallback to default if null
     */
    margins?: RenderOptionsMargins;
    pageFormat?: 'A0' | 'A1' | 'A2' | 'A3' | 'A4' | 'A5' | 'A6' | 'Letter' | 'Legal';
    /**
     * page size in mm; overrides page format
     */
    pageSize?: PageSize;
};

export type RenderOptionsMargins = {
    /**
     * margin bottom in mm
     */
    bottom?: number;
    /**
     * margin left in mm
     */
    left?: number;
    /**
     * margin right in mm
     */
    right?: number;
    /**
     * margin top in mm
     */
    top?: number;
};

export type RenderTemplateData = {
    /**
     * Optional template for footer. If empty, the footer template will be parsed from main template (<PdfFooter></PdfFooter>).
     */
    footerHtmlTemplate?: string;
    /**
     * Optional template for header. If empty, the header template will be parsed from main template (<PdfHeader></PdfHeader>).
     */
    headerHtmlTemplate?: string;
    htmlTemplate?: string;
    /**
     * Model with your data matching to the templates
     */
    model?: {
        [key: string]: unknown;
    };
    options?: RenderOptions;
    templateEngine?: 'golang' | 'handlebars' | 'django';
};

export type TemplateTestResult = {
    bodyTemplateError?: string;
    footerTemplateError?: string;
    headerTemplateError?: string;
    isValid?: boolean;
};

export type PostApiPdfFromHtmlBundleRenderData = {
    body: {
        /**
         * Bundle Zip-File
         */
        bundle: Blob | File;
        /**
         * JSON-Model for template (only required for template)
         */
        model?: string;
        /**
         * Template engine to use for template (only required for template)
         */
        templateEngine?: string;
    };
    path?: never;
    query?: never;
    url: '/api/pdf/from/html-bundle/render';
};

export type PostApiPdfFromHtmlBundleRenderResponses = {
    /**
     * PDF File
     */
    200: Blob | File;
};

export type PostApiPdfFromHtmlBundleRenderResponse = PostApiPdfFromHtmlBundleRenderResponses[keyof PostApiPdfFromHtmlBundleRenderResponses];

export type PostApiPdfFromHtmlTemplateRenderData = {
    /**
     * Render Data
     */
    body: RenderTemplateData;
    path?: never;
    query?: never;
    url: '/api/pdf/from/html-template/render';
};

export type PostApiPdfFromHtmlTemplateRenderResponses = {
    /**
     * PDF File
     */
    200: Blob | File;
};

export type PostApiPdfFromHtmlTemplateRenderResponse = PostApiPdfFromHtmlTemplateRenderResponses[keyof PostApiPdfFromHtmlTemplateRenderResponses];

export type PostApiPdfFromHtmlTemplateTestData = {
    /**
     * Render Data
     */
    body: RenderTemplateData;
    path?: never;
    query?: never;
    url: '/api/pdf/from/html-template/test';
};

export type PostApiPdfFromHtmlTemplateTestResponses = {
    /**
     * OK
     */
    200: TemplateTestResult;
};

export type PostApiPdfFromHtmlTemplateTestResponse = PostApiPdfFromHtmlTemplateTestResponses[keyof PostApiPdfFromHtmlTemplateTestResponses];

export type PostApiPdfFromHtmlRenderData = {
    /**
     * Render Data
     */
    body: RenderData;
    path?: never;
    query?: never;
    url: '/api/pdf/from/html/render';
};

export type PostApiPdfFromHtmlRenderResponses = {
    /**
     * PDF File
     */
    200: Blob | File;
};

export type PostApiPdfFromHtmlRenderResponse = PostApiPdfFromHtmlRenderResponses[keyof PostApiPdfFromHtmlRenderResponses];

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * OK
     */
    200: unknown;
};
